apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-entrypoint
  namespace: {{ .System.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Owner }}
  ownerReferences:
    - {{- . | toYaml | nindent 6 }}
  {{- end }}
data:
  entrypoint.sh: |
    {{- file "vault/entrypoint.sh" | nindent 4 }}