apiVersion: rbac.authorization.k8s.io/v1
kind: Role
{{ include "metadata" . }}
rules: 
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ instanceName }}-unseal-key
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ instanceName }}-root-ca
    verbs:
      - get
      - update
      - patch
      - delete