apiVersion: v1
kind: Service
{{ include "metadata" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "selectors" . | nindent 4 }}
  ports:
    - name: https
      port: 8200
      targetPort: 8200
      protocol: TCP
