apiVersion: apps/v1
kind: StatefulSet
{{ include "metadata" . }}
spec:
  serviceName: {{ componentFullName }}
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "selectors" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ componentFullName }}
      {{- with .App.ImagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      {{- include "podSecurityContext" . | nindent 6 }}
      containers:
        - name: {{ .Component.Name }}
          image: {{ .Component.Image | default (printf "%s/%s:%s" .App.Registry .Component.Name .Component.Commit) | quote }}
          imagePullPolicy: {{ .Component.ImagePullPolicy | default "IfNotPresent" }}
          {{- include "containerSecurityContext" . | nindent 10 }}
          resources:
            requests:
              memory: 115Mi # 90% of limit, used to set GOMEMLIMIT 
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 1000m
          env:
            - name: KUBEFOX_INSTANCE
              value: {{ .Instance.Name }}
            - name: KUBEFOX_NAMESPACE
              value: {{ namespace }}
            - name: VAULT_LOG_FORMAT
              value: {{ .Values.logFormat | default "json" }}
          ports:
            - name: https
              containerPort: 8200
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -ec
                - vault status -tls-skip-verify
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: entrypoint
              mountPath: /usr/local/bin/docker-entrypoint.sh
              subPath: entrypoint.sh
            - name: home
              mountPath: /home/vault
            - name: data
              mountPath: /vault/data
      volumes:
        - name: entrypoint
          configMap:
            defaultMode: 0777
            name: {{ componentFullName }}-entrypoint
        - name: home
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volumeSize | default "1Gi" }}
