apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Instance.Name }}-root-ca
  namespace: {{ namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
  {{- with .Owner }}
  ownerReferences:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
data:
  ca.crt: |
    {{- .Instance.RootCA | nindent 4 }}
