apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ name }}-env
  namespace: {{ namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Component.Annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Owner }}
  ownerReferences:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
data:
  KUBEFOX_HOME: {{ homePath | quote }}
  KUBEFOX_INSTANCE_NAMESPACE: {{ .Instance.Namespace | quote }}
  KUBEFOX_INSTANCE: {{ .Instance.Name  | quote }}
  KUBEFOX_NAMESPACE: {{ namespace | quote }}
  KUBEFOX_PLATFORM_FULL_NAME: {{ platformFullName | quote }}
  KUBEFOX_PLATFORM_NAMESPACE: {{ .Platform.Namespace | quote }}
  KUBEFOX_PLATFORM_VAULT_NAME: {{ platformVaultName | quote }}
  KUBEFOX_PLATFORM: {{ .Platform.Name | quote }}
  {{- with .Logger.Format }}
  KUBEFOX_LOG_FORMAT: {{ . | quote }}
  {{- end }}
  {{- with .Logger.Level }}
  KUBEFOX_LOG_LEVEL: {{ . | quote }}
  {{- end }}
