apiVersion: apps/v1
kind: Deployment
{{ include "metadata" . }}
spec:
  selector:
    matchLabels:
      {{- include "selectors" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      {{- include "podSpec" . | nindent 6 }}
      containers:
        - name: {{ .Component.Name }}
          image: {{ .Component.Image | default (printf "%s/%s:%s" .App.Registry .Component.Name .Component.Commit) | quote }}
          imagePullPolicy: {{ .Component.ImagePullPolicy | default "IfNotPresent" }}
          {{- include "containerSecurityContext" . | nindent 10 }}
          args:
            - -name={{ .Component.Name }}
            - -commit={{ .Component.Commit }}
            - -broker-addr=$(KUBEFOX_HOST_IP):6060
            - -health-addr=0.0.0.0:1111
            - -log-format={{ logFormat }}
            - -log-level={{ logLevel }}
          {{- if .Component.Resources }}
          resources:
            {{- .Component.Resources | toYaml | nindent 12 }}
          {{- else if .App.Resources }}
          resources:
            {{- .App.Resources | toYaml | nindent 12 }}
          {{- end }}
          env:
          {{- include "env" . | nindent 12 }}
            - name: KUBEFOX_COMPONENT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: {{ name }}-env
          ports:
            - name: health
              containerPort: 1111
              protocol: TCP
          readinessProbe:
            periodSeconds: 3
            failureThreshold: 2
            httpGet:
              port: health
          livenessProbe:
            failureThreshold: 6
            httpGet:
              port: health
          volumeMounts:
            - name: root-ca
              mountPath: {{ homePath }}/ca.crt
              subPath: ca.crt
      volumes:
        - name: root-ca
          configMap:
            name: {{ .Instance.Name }}-root-ca
