apiVersion: apps/v1
kind: Deployment
{{ include "metadata" . }}
spec:
  selector:
    matchLabels:
      {{- include "selectors" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ componentFullName }}
      {{- with .App.ImagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      {{- include "podSecurityContext" . | nindent 6 }}
      containers:
        - name: {{ .Component.Name }}
          image: {{ .Component.Image | default (printf "%s/%s:%v" .App.Registry .Component.Name .Component.Commit) | quote }}
          imagePullPolicy: {{ .Component.ImagePullPolicy | default "IfNotPresent" }}
          {{- include "containerSecurityContext" . | nindent 10 }}
          args:
            - -name={{ .Component.Name }}
            - -commit={{ .Component.Commit }}
            - -broker-addr=$(BROKER_HOST):6060
            - -log-format=json
            - -log-level=info
          env:
            - name: BROKER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: {{ .Platform.Name }}-env
          volumeMounts:
            - name: root-ca
              mountPath: /tmp/kubefox/broker/ca.crt
              subPath: ca.crt
      volumes:
        - name: root-ca
          configMap:
            name: {{ .Instance.Name }}-root-ca
