apiVersion: v1
kind: Service
metadata:
  name: kfp-runtime-server
  namespace: kubefox-system
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 7071
    protocol: TCP
    targetPort: 7071
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kfp-runtime-server
  namespace: kubefox-system
subsets:
- addresses:
  - ip: 192.168.1.2
