apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Instance.Name }}-pki-init
  namespace: {{ namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Owner }}
  ownerReferences:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
data:
  pki-init.sh: |
    {{- file "pki-init.sh" | nindent 4 }}