apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ name }}-env
  namespace: {{ namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Owner }}
  ownerReferences:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
data:
  KUBEFOX_HOME: {{ homePath | quote }}
  KUBEFOX_INSTANCE_NAMESPACE: {{ .Instance.Namespace | quote }}
  KUBEFOX_INSTANCE: {{ .Instance.Name | quote }}
  KUBEFOX_NAMESPACE: {{ namespace | quote }}
  {{- with .Platform.LogFormat }}
  KUBEFOX_LOG_FORMAT: {{ . | quote }}
  {{- end }}
  {{- with .Platform.LogLevel }}
  KUBEFOX_LOG_LEVEL: {{ . | quote }}
  {{- end }}