apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ name }}-operator
  namespace: {{ namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Component.Annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Owner }}
  ownerReferences:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
webhooks:
  - name: platform-mutation.kubefox.xigxog.io
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Values.caBundle }}
      service:
        name: {{ name }}-operator
        namespace: {{ namespace }}
        path: /v1alpha1-platform/mutate
    rules:
      - apiGroups:
          - kubefox.xigxog.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - platforms
  
  - name: release-mutation.kubefox.xigxog.io
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Values.caBundle }}
      service:
        name: {{ name }}-operator
        namespace: {{ namespace }}
        path: /v1alpha1-release/mutate
    rules:
      - apiGroups:
          - kubefox.xigxog.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - releases