apiVersion: v1
kind: Service
metadata:
  name: {{ .Platform.Name }}-broker
  namespace: {{ .System.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Owner }}
  ownerReferences:
    - {{- . | toYaml | nindent 6 }}
  {{- end }}
spec:
  type: ExternalName
  externalName: 127.0.0.1
