apiVersion: v1
kind: Service
{{ include "metadata" . }}
spec:
  type: NodePort
  selector:
    {{- include "selectors" . | nindent 4 }}
  ports:
    - port: 80
      name: "web"
      targetPort: web
      protocol: TCP
      nodePort: 30080
    - port: 443
      name: "websecure"
      targetPort: websecure
      protocol: TCP
      nodePort: 30443
