apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: {{ .Platform.Name }}-operator
  namespace: {{ .System.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Owner }}
  ownerReferences:
    - {{- . | toYaml | nindent 6 }}
  {{- end }}
spec:
  resources:
    - apiVersion: k8s.kubefox.io/v1alpha1
      resource: componentsets
    - apiVersion: k8s.kubefox.io/v1alpha1
      resource: platforms
    - apiVersion: k8s.kubefox.io/v1alpha1
      resource: releases
  attachments:
    - apiVersion: v1
      resource: configmaps
      updateStrategy:
        method: InPlace
    - apiVersion: v1
      resource: namespaces
    - apiVersion: v1
      resource: secrets
      updateStrategy:
        method: InPlace
    - apiVersion: apps/v1
      resource: deployments
    - apiVersion: batch/v1
      resource: cronjobs
      updateStrategy:
        method: Recreate
    - apiVersion: k8s.kubefox.io/v1alpha1
      resource: componentsets
    - apiVersion: metacontroller.k8s.io/v1alpha1
      resource: compositecontrollers
      updateStrategy:
        method: Recreate
    - apiVersion: metacontroller.k8s.io/v1alpha1
      resource: decoratorcontrollers
      updateStrategy:
        method: Recreate
    - apiVersion: traefik.io/v1alpha1
      resource: ingressroutes
      updateStrategy:
        method: Recreate
    - apiVersion: traefik.io/v1alpha1
      resource: middlewares
      updateStrategy:
        method: Recreate
  hooks:
    sync:
      webhook:
        url: https://{{ .Platform.Name }}-operator/sync?kf-release-event-type=io.kubefox.kubernetes_request
    customize:
      webhook:
        url: https://{{ .Platform.Name }}-operator/customize?kf-release-event-type=io.kubefox.kubernetes_request
