apiVersion: apps/v1
kind: DaemonSet
{{ include "metadata" . }}
spec:
  selector:
    matchLabels:
      {{- include "selectors" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ componentName }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .App.ImagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Component.Name }}
          image: {{ .Component.Image | default (printf "%s/%s:%v" .App.Registry .Component.Name .Component.Commit) | quote }}
          imagePullPolicy: {{ .Component.ImagePullPolicy | default "IfNotPresent" }}
          args:
            - -instance={{ .Instance.Name }}
            - -platform={{ .Platform.Name }}
            - -namespace={{ .Platform.Namespace }}
            - -grpc-addr=$(BROKER_HOST):6060
            - -vault-addr={{ .Instance.Name }}-vault.{{ .Instance.Namespace }}
            - -nats-addr={{ .Platform.Name }}-nats.{{ .Platform.Namespace }}
            - -http-addr=0.0.0.0:8080
            - -telemetry-addr=false
            - -health-addr=0.0.0.0:1111
            - -log-format=json
            - -log-level=info
          env:
            - name: BROKER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: grpc
              containerPort: 6060
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 1111
              protocol: TCP
          readinessProbe:
            httpGet:
              port: health
          livenessProbe:
            httpGet:
              port: health
          volumeMounts:
            - name: root-ca
              mountPath: /tmp/kubefox/broker/ca.crt
              subPath: ca.crt
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
      volumes:
        - name: root-ca
          configMap:
            name: {{ .Instance.Name }}-root-ca
