apiVersion: apps/v1
kind: DaemonSet
{{ include "metadata" . }}
spec:
  selector:
    matchLabels:
      {{- include "selectors" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ componentFullName }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .App.ImagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      {{- include "podSecurityContext" . | nindent 6 }}
      initContainers:
        - name: pki-init
          image: {{ .Values.pkiInitImage | quote }}
          imagePullPolicy: {{ .Component.ImagePullPolicy | default "IfNotPresent" }}
          {{- include "containerSecurityContext" . | nindent 10 }}
          command:
            - /pki-init.sh
          env:
            - name: KUBEFOX_HOME
              value: /tmp/kubefox
            - name: KUBEFOX_COMPONENT
              value: {{ .Component.Name }}
            - name: KUBEFOX_COMPONENT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: {{ .Platform.Name }}-env
          volumeMounts:
            - name: pki-init
              mountPath: /pki-init.sh
              subPath: pki-init.sh
            - name: root-ca
              mountPath: /tmp/kubefox/ca.crt
              subPath: ca.crt
            - name: kubefox
              mountPath: /tmp/kubefox
      containers:
        - name: {{ .Component.Name }}
          image: {{ .Component.Image | default (printf "%s/%s:%s" .App.Registry .Component.Name .Component.Commit) | quote }}
          imagePullPolicy: {{ .Component.ImagePullPolicy | default "IfNotPresent" }}
          {{- include "containerSecurityContext" . | nindent 10 }}
          args:
            - -instance={{ .Instance.Name }}
            - -platform={{ .Platform.Name }}
            - -namespace={{ .Platform.Namespace }}
            - -grpc-addr=$(KUBEFOX_COMPONENT_IP):6060
            - -vault-addr={{ .Instance.Name }}-vault.{{ .Instance.Namespace }}
            - -nats-addr={{ .Platform.Name }}-nats.{{ .Platform.Namespace }}
            - -http-addr=0.0.0.0:8080
            - -telemetry-addr=false
            - -health-addr=0.0.0.0:1111
            - -log-format=json
            - -log-level=info
          env:
            - name: KUBEFOX_COMPONENT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: {{ .Platform.Name }}-env
          ports:
            - name: grpc
              containerPort: 6060
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 1111
              protocol: TCP
          readinessProbe:
            httpGet:
              port: health
          livenessProbe:
            httpGet:
              port: health
          volumeMounts:
            - name: root-ca
              mountPath: /tmp/kubefox/ca.crt
              subPath: ca.crt
            - name: kubefox
              mountPath: /tmp/kubefox
      volumes:
        - name: root-ca
          configMap:
            name: {{ .Instance.Name }}-root-ca
        - name: pki-init
          configMap:
            name: {{ .Platform.Name }}-pki-init
            defaultMode: 0777
        - name: kubefox
          emptyDir: {}