apiVersion: apps/v1
kind: DaemonSet
{{ include "metadata" . }}
spec:
  selector:
    matchLabels:
      {{- include "selectors" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      {{- include "podSpec" . | nindent 6 }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - {{- include "bootstrap" . | nindent 10 }}
      containers:
        - name: {{ .Component.Name }}
          image: {{ .Component.Image | quote }}
          imagePullPolicy: {{ .Component.ImagePullPolicy | default "IfNotPresent" }}
          {{- include "securityContext" . | nindent 10 }}
          {{- include "resources" . | nindent 10 }}
          {{- include "probes" . | nindent 10 }}
          args:
            - -instance={{ .Instance.Name }}
            - -platform={{ .Platform.Name }}
            - -namespace={{ namespace }}
            - -grpc-addr=$(KUBEFOX_COMPONENT_IP):6060
            - -nats-addr={{ .Platform.Name }}-nats.{{ .Platform.Namespace }}
            - -telemetry-addr=false
            - -health-addr=0.0.0.0:1111
            - -log-format={{ .Logger.Format | default "json" }}
            - -log-level={{ .Logger.Level | default "info" }}
          env:
          {{- include "env" . | nindent 12 }}
            - name: KUBEFOX_COMPONENT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: {{ .Component.Name }}
                  resource: requests.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  containerName: {{ .Component.Name }}
                  resource: limits.cpu
          envFrom:
            - configMapRef:
                name: {{ name }}-env
          ports:
            - name: grpc
              containerPort: 6060
              protocol: TCP
            - name: health
              containerPort: 1111
              protocol: TCP
          volumeMounts:
            - name: root-ca
              mountPath: {{ homePath }}/ca.crt
              subPath: ca.crt
            - name: kubefox
              mountPath: {{ homePath }}
      volumes:
        - name: root-ca
          configMap:
            name: {{ .Instance.Name }}-root-ca
        - name: kubefox
          emptyDir: {}