apiVersion: rbac.authorization.k8s.io/v1
kind: Role
{{ include "metadata" . }}
rules:
  - apiGroups:
      - kubefox.xigxog.io
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - list
      - get
      - watch