apiVersion: v1
kind: Service
metadata:
  name: {{ .Component.Name }}-headless
  namespace: {{ namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Component.Annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Owner }}
  ownerReferences:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "selectors" . | nindent 4 }}
  ports:
    - name: grpc
      port: 6060
      targetPort: 6060
      protocol: TCP
