apiVersion: v1
kind: Service
metadata:
  name: {{ .System.Name }}-broker
  namespace: {{ .System.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: 127.0.0.1
