apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ componentFullName }}-config
  namespace: {{ namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Component.Annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Owner }}
  ownerReferences:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
data:
  nats.conf: |
    {{- file "nats/nats.conf" | nindent 4 }}