apiVersion: v1
kind: Service
{{ include "metadata" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "selectors" . | nindent 4 }}
  ports:
    - name: client
      port: 4222
      protocol: TCP
